name: Release Unity Package

on:
  push:
    branches:
      - master

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{steps.package_name.outputs.package_name}}
    steps:
      - id: package_name
        #run: echo "::set-output name=package_name::$(echo ${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/})"
        run: echo "::set-output name=package_name::$(echo ${GITHUB_REPOSITORY##*/})"

  release:
    needs: prebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci

      - run: |
          find Assets -name \*.meta > metaList
          mkdir dist
          cat metaList

      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'dist/${{needs.prebuild.outputs.package_name}}.unitypackage'
          include-files: metaList

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
