name: Release
on: push

env:
  packageName: "com.nekometer.esnya.udon-sun-controller"

permissions:
  contents: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci

      - id: prev_version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with:
            path: "Packages/${{env.packageName}}/package.json"
            prop_path: "version"

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with:
            path: "Packages/${{env.packageName}}/package.json"
            prop_path: "version"
    outputs:
      prev_version: ${{ steps.prev_version.outputs.prop }}
      next_version: ${{ steps.version.outputs.prop }}

  vcc-release:
    runs-on: ubuntu-latest
    needs: semantic-release
    if: needs.semantic-release.outputs.prev_version != needs.semantic-release.outputs.next_version
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v${{ needs.semantic-release.outputs.next_version }}
      - run: echo "version=${{ needs.semantic-release.outputs.next_version }}" >> $GITHUB_ENV

      - run: |
          echo "zipFile=${{ env.packageName }}-${{ env.version }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ env.packageName }}-${{ env.version }}.unitypackage" >> $GITHUB_ENV
      - uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "Packages/${{env.packageName}}/"
          filename: "../../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above

      - run: find "Packages/${{env.packageName}}/" -name \*.meta >> metaList
      - uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList

      - uses: svenstaro/upload-release-action@v2
        with:
          tag: v${{ env.version }}
          file: ${{ env.zipFile }}
      - uses: svenstaro/upload-release-action@v2
        with:
          tag: v${{ env.version }}
          file: ${{ env.unityPackage }}
      - uses: svenstaro/upload-release-action@v2
        with:
          tag: v${{ env.version }}
          file: Packages/${{ env.packageName }}/package.json
      - run: |
          TOKEN=${{ secrets.VCC_PACKAGES_TOKEN }}
          OWNER=esnya
          REPO=vcc-packages

          curl \
            -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO/dispatches \
            -d '{"event_type":"build-listing","client_payload":{}}'
